TEC-82: Allow leading zero date entry
AnikaLegal/intake pull request #21
Opened 2024-05-09 10:42 UTC by ziggygio

[TEC-86 : Allow leading zero date entry](https://linear.app/anika-legal/issue/TEC-86/allow-leading-zero-date-entry)

Changes the input type of day and month in the date input from number to text to support leading zeros. Also includes additional logic to handle invalid inputs.

Screenshot:
<img width="1491" alt="image" src="https://github.com/AnikaLegal/intake/assets/85324964/00d18b50-4e32-4304-83d3-9c728211bdd8">

2024-05-10 03:02 UTC, luca-vari requested changes
Hi Zach, hope you're well! Thanks for this and sorry I didn't get back earlier but seems like you have come up with a good solution. I have added a few review comments. Could you please look over them?

2024-05-10 03:02 UTC, luca-vari commented on src/design/inputs/date.js
> -  useEffect(() => {
Hi Zach, we need to keep the `useEffect` here as this is used to populate the date values from the users local storage. It's a bit convoluted, see [here](https://github.com/AnikaLegal/intake/blob/8a7db38eab85a8db223a40527581202993034611/src/views/form.js#L27), the loadFormData method loads some json from local storage and those values are ultimately passed through to the rendered components.  With your change, if you navigate from a "date" question to the next question and back again you'll see that the date you entered previously is now not displayed. Similarly, if the user closes the tab of the intake form but comes back to complete it later we want to display the values they used previously. 

I think I understand why you removed it as it sets leading-zero date values to single digit values every time the date component renders, which looks strange. I think we can keep the `useEffect` and prevent the strange behaviour if we adjust the [effect dependencies to be an empty array](https://react.dev/learn/lifecycle-of-reactive-effects#what-an-effect-with-empty-dependencies-means). 
```
  useEffect(() => {
    // ...
  }, [])
```
This means that the effect only occurs once when the component mounts. This is probably how it should always have been.

2024-05-10 03:02 UTC, luca-vari commented on src/design/inputs/date.js
> +  const onDateChange = (newDate) => {
```suggestion
  const dateChange = (newDate) => {
```
Not a big deal but I would usually reserve function names starting with "on" for event handlers. Refactoring all of the duplicate code into a single method is a great change but since we don't, for example, pass that function to another component to call when some specific behaviour happens, we shouldn't use a name that implies that is what it is used for. It's more like a helper function local to this component.

2024-05-10 03:02 UTC, luca-vari commented on src/design/inputs/date.js
Keep the type checker happy! :smile: 

```
const getDateFromVals = (
  y: number | string | null,
  m: number | string | null,
  d: number | string | null
) => {
```

2024-05-10 11:18 UTC, ziggygio commented on src/design/inputs/date.js
> -  useEffect(() => {
Added this back in, it works with the empty array in useEffect

2024-05-10 11:18 UTC, ziggygio commented on src/design/inputs/date.js
> +  const onDateChange = (newDate) => {
Fair point! Changed this.

2024-05-10 11:19 UTC, ziggygio commented on src/design/inputs/date.js
Fixed this! I only changed the day and month inputs to strings so left year - unless you think I should change the year input for consistency?

2024-05-13 01:57 UTC, luca-vari commented on src/design/inputs/date.js
Hi Zach, hope you had a good weekend! 

For this one I would leave the year as-is, that is, keep this bit the same:

`  const [year, setYear] = useState<number | null>(null)
`

but just add `string` to the types that we allow for all of the arguments on the  `getDateFromVals` function:

```
  y: number | string | null,
  m: number | string | null,
  d: number | string | null
```

The type annotations should reflect the types that the function can accept. Since the function can handle numbers, strings & null (although null doesn't seem very useful! :smile:) we can annotate the type for both `number` & `string`. Ultimately we just join the values to a `string` anyway:

`
[y, m, d].join('-')`

To my mind this is better than having a method that, ignoring null, expects a mix of types:

```
  y: number | null,
  m: string | null,
  d: string | null
```

The other options are:

- Change the type of the year variable to a string i.e.  `const [year, setYear] = useState<string | null>(null)` and set all of the annotations to `string`. That would require more work & testing however.
- Just remove the type annotations from the function. They're not super useful and the other date functions in that file don't have type annotations.

What do you think?

2024-05-20 11:31 UTC, ziggygio commented on src/design/inputs/date.js
Hey Luca, I personally think the best option would be to keep it as is. Even though it can accept all types for all the arguments, the code is only handling years as numbers and months/days as strings so it would prevent errors in case we ever got a string year, for example. I don't see an issue in expecting different types for different arguments, but I'm happy to change it if you disagree. My preferred option would then be to change year to a string so we're not typing it to accept more than what we'd expect, it's getting close to just saying `y: any`

Although at the end of the day it is a JavaScript file so it makes no difference 😋

2024-05-21 23:28 UTC, luca-vari commented on src/design/inputs/date.js
Hi Zach, I'm happy for you to proceed as you prefer. As you rightly point out, it's not a big issue :smile: Once you are happy then please merge.

2024-05-21 23:31 UTC, luca-vari approved these changes

2024-06-10 01:34 UTC, merged